#!/usr/bin/env bash
# display To infinity and beyond by using the while loop indefinitely whil each iteration of the loop, add a sleep 2
i=1
while [ $i ]
do
		echo "To infinity and beyond"
			sleep 2
		done
