#!/usr/bin/env bash
# a bash script that displays to infinity and beyond indefinitly with a sleep 2 in between each iteration. i am invinvcible!!! when receiving a sigterm signal
i=1
while [ $i ]
do
                echo "To infinity and beyond"
                        sleep 2
trap 'echo "I am invincible!!!"' 15
done
