#!/usr/bin/env bash
# display Best School 10 times, but for the 9th iteration, displays Best School and then hi on a new line

i=1

while [ $i -lt 10 ]
do
if [ ${count -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
(( i++ ))
done
