#!/usr/bin/env bash
# a Bash script that gives you information about the school file

file=school

if [ -e $file ];
then
echo "school file exists"
else
echo "school file is not empty"
exit 1
fi

if [ ! -s $file ];
then
echo "school is empty"
fi

if [ -f $file ];
then
	echo "school is a regular file"
fi
